Insert into Conturi(numarCont, nume, car) values 
('101','Capital',true),
('1063.01','Rezerve statutare',false),
('1063.02','Rezerve de risc',false),
('113.01.01','Fondul social al membrilor CAR',true),
('114','Fondul pentru ajutor de deces al membrilor CAR',false),
('1211.01','Excedent sau deficit priving activitatile fara scop patrimonial',false),
('1291.01','Repartizarea rezultatului exercitiului',false),
('2678.01.01.01','Imprumuturi curente',true),
('2679.01.01','Dobinzi asupra imprumuturilor curente',true),
('3028','Materiale auxiliare',false),
('303','Obiecte de inventar',false),
('401.01','Alti furnizori',false),
('401.02','Furnizori - Colaboratori',false),
('4311.02','Contributia unitatii la asigurarile sociale (CAS) - Colaboratori',false),
('4312.02','Contributia colaboratorilor la asigurarile sociale',false),
('4313.02','Contributia angajatorului pentru asigurarile sociale de sanatate - Colaboratori',false),
('4313.04','Contributia angajatorului pentru concedii si indemnizatii - Colaboratori',false),
('4314.02','Contributia pentru asigurarile sociale de sanatate - Colaboratori',false),
('4371.02','Contributia unitatii la fondul de somaj - Colaboratori',false),
('4372.02','Contributia personalului la fonul de somaj - Colaboratori',false),
('444.02','Impozit - Colaboratori',false),
('4511.01','Decontari privind contributia statutara a caselor de ajutor reciproc catre uniunea teritoriala judeteana',false),
('472.01.01.01','Venituri de realizat privind dobinzile aferente imprumuturilor curente',true),
('5121','Conturi la banci in lei',true),
('5311','Casa in lei',true),
('581','Viramente interne',false),
('6028','Cheltuieli privind materialele consumabile',false),
('603','Cheltuieli privind obiecte de inventar',false),
('621','Cheltuieli cu colaboratorii',false),
('627','Cheltuieli cu servicii bancare',false),
('635','Cheltuieli cu alte impozite si taxe',false),
('6451.02','Contributia unitatii la asigurarile sociale - Colaboratori',false),
('6452.02','Contributia unitatii pentru ajutorul somaj - Colaboratori',false),
('6453.02','Contributia angajatorului pentru asigurarile sociale de sanatate - Colaboratori',false),
('6453.03','Contributia angajatorului pentru concedii si indemnizatii',false),
('6551','Cotizatii si contributii',false),
('7341.01.01.01','Venituri din dobinzile obtinute pentru imprumuturi curente',false)

;